[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.12.0"
  PNPM_VERSION = "10.5.2"
  NPM_FLAGS = "--production=false"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
